In [1]:
#import nessary models

import numpy as np
import pandas as pd
import matplotlib.pyplot as mlt

In [2]:
#read the dataset
df=pd.read_csv("churn.csv")

In [3]:
df.shape



(19158, 14)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   enrollee_id             19158 non-null  int64  
 1   city                    19158 non-null  object 
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object 
 4   relevent_experience     19158 non-null  object 
 5   enrolled_university     18772 non-null  object 
 6   education_level         18698 non-null  object 
 7   major_discipline        16345 non-null  object 
 8   experience              19093 non-null  object 
 9   company_size            13220 non-null  object 
 10  company_type            13018 non-null  object 
 11  last_new_job            18735 non-null  object 
 12  training_hours          19158 non-null  int64  
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
me

In [5]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
last_new_job               423
training_hours               0
target                       0
dtype: int64

In [6]:
# split numeric feature and objct feature datatype 

objectvalue=[]
numvalue=[]
for nu in df.columns:
    if df[nu].dtype=="object":
       objectvalue.append(nu)
    else:    
        numvalue.append(nu)
    

In [7]:

objectvalue

['city',
 'gender',
 'relevent_experience',
 'enrolled_university',
 'education_level',
 'major_discipline',
 'experience',
 'company_size',
 'company_type',
 'last_new_job']

In [8]:
numvalue

['enrollee_id', 'city_development_index', 'training_hours', 'target']

In [9]:
# the numeric dtype feature not null values plased
df[numvalue].isnull().sum()

enrollee_id               0
city_development_index    0
training_hours            0
target                    0
dtype: int64

In [10]:
# object dtype feature has more null value

df[objectvalue].isnull().sum()

city                      0
gender                 4508
relevent_experience       0
enrolled_university     386
education_level         460
major_discipline       2813
experience               65
company_size           5938
company_type           6140
last_new_job            423
dtype: int64

In [11]:
# i fill nullvalue places insert mode value of the feature
for f in objectvalue:
    if df[f].isnull().sum() != 0 :
       modev=df[f].mode()[0]
       df[f].fillna(modev,inplace=True)

In [12]:
df.isnull().sum()

enrollee_id               0
city                      0
city_development_index    0
gender                    0
relevent_experience       0
enrolled_university       0
education_level           0
major_discipline          0
experience                0
company_size              0
company_type              0
last_new_job              0
training_hours            0
target                    0
dtype: int64

In [13]:
df.describe()

enrollee_id  city_development_index  training_hours        target
count  19158.000000            19158.000000    19158.000000  19158.000000
mean   16875.358179                0.828848       65.366896      0.249348
std     9616.292592                0.123362       60.058462      0.432647
min        1.000000                0.448000        1.000000      0.000000
25%     8554.250000                0.740000       23.000000      0.000000
50%    16982.500000                0.903000       47.000000      0.000000
75%    25169.750000                0.920000       88.000000      0.000000
max    33380.000000                0.949000      336.000000      1.000000

In [14]:
# find the balanced or imbalanced dataset

df['target'].value_counts()

target
0.0    14381
1.0     4777
Name: count, dtype: int64

In [15]:
# its a imbalanced dataset, when i will evalation metrics use "Presition" and "recall"
# becausethe target unique values,one unique value has above 10000 values
# but another unique value has above 4000 only

In [16]:
#find the unique value of the object datatype

df[objectvalue].nunique()

city                   123
gender                   3
relevent_experience      2
enrolled_university      3
education_level          5
major_discipline         6
experience              22
company_size             8
company_type             6
last_new_job             6
dtype: int64

In [17]:
# split ordered chategorical feature and nominal chategorical feature

targete=[]
labele=[]
for d in objectvalue:
    if df[d].nunique()>3:
        targete.append(d)
    else:
        labele.append(d)
    

In [18]:
#it is ordinal chategorical feature
for s in labele:
    gh=df[s].unique()
    print(s)
    print()
    print(gh)
    print()

gender

['Male' 'Female' 'Other']

relevent_experience

['Has relevent experience' 'No relevent experience']

enrolled_university

['no_enrollment' 'Full time course' 'Part time course']



In [19]:
# import encoders
# ordinal features change to numeric values used to labelencoder
# nominal features change to numeric values used to Target encoder

from sklearn.preprocessing import LabelEncoder
from category_encoders import TargetEncoder

for la in labele:
    labe=LabelEncoder()
    df[la]=labe.fit_transform(df[la])
for ta in targete:
    tae=TargetEncoder()
    df[ta]=tae.fit_transform(df[ta],df['target'])


In [20]:
df['target']=LabelEncoder().fit_transform(df['target'])

In [21]:
df

enrollee_id      city  city_development_index  gender  \
0             8949  0.213088                   0.920       1   
1            29725  0.147894                   0.776       1   
2            11561  0.591044                   0.624       1   
3            33241  0.384382                   0.789       1   
4              666  0.289062                   0.767       1   
...            ...       ...                     ...     ...   
19153         7386  0.125828                   0.878       1   
19154        31398  0.213088                   0.920       1   
19155        24576  0.213088                   0.920       1   
19156         5756  0.137143                   0.802       1   
19157        23834  0.132251                   0.855       1   

       relevent_experience  enrolled_university  education_level  \
0                        0                    2         0.277741   
1                        1                    2         0.277741   
2                        1                    0         0.277741   
3                        1                    2         0.277741   
4                        0                    2         0.214400   
...                    ...                  ...              ...   
19153                    1                    2         0.277741   
19154                    0                    2         0.277741   
19155                    0                    2         0.277741   
19156                    0                    2         0.195340   
19157                    1                    2         0.133117   

       major_discipline  experience  company_size  company_type  last_new_job  \
0              0.250795    0.156968      0.327569      0.260638      0.269290   
1              0.250795    0.166181      0.327569      0.260638      0.182371   
2              0.250795    0.288112      0.327569      0.260638      0.301387   
3              0.262997    0.454023      0.327569      0.260638      0.301387   
4              0.250795    0.156968      0.327569      0.139860      0.221574   
...                 ...         ...           ...           ...           ...   
19153          0.210762    0.182594      0.327569      0.260638      0.269290   
19154          0.250795    0.182594      0.327569      0.260638      0.221574   
19155          0.250795    0.156968      0.327569      0.260638      0.221574   
19156          0.250795    0.454023      0.173318      0.260638      0.241379   
19157          0.250795    0.331854      0.327569      0.260638      0.269290   

       training_hours  target  
0                  36       1  
1                  47       0  
2                  83       0  
3                  52       1  
4                   8       0  
...               ...     ...  
19153              42       1  
19154              52       1  
19155              44       0  
19156              97       0  
19157             127       0  

[19158 rows x 14 columns]

In [22]:
#find the correlation between target and independent variable

co=abs(df.corr()['target']).sort_values(ascending=False)
co

target                    1.000000
city                      0.391860
city_development_index    0.341665
experience                0.189915
company_size              0.175930
enrolled_university       0.149539
relevent_experience       0.128430
education_level           0.091517
last_new_job              0.085674
company_type              0.068991
enrollee_id               0.049475
training_hours            0.021577
major_discipline          0.021290
gender                    0.006733
Name: target, dtype: float64

In [23]:
# filter bad correlation features

badcor=co[co<0.06]

In [24]:
badcor

enrollee_id         0.049475
training_hours      0.021577
major_discipline    0.021290
gender              0.006733
Name: target, dtype: float64

In [25]:
#drop the bad correlation feature into datset
df.drop(badcor.index,axis=1,inplace=True)

In [26]:
df.shape

(19158, 10)

In [27]:
# split independent variable and dependent variable

X=df.drop('target',axis=1)

In [28]:
X.shape

(19158, 9)

In [29]:
y=df['target']


In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.10,random_state=42)

In [31]:
# import classification algorithums and metrics
# it is imbalanced dataset so, i used presition ,recall,f1 score metrics

from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score

models=[DecisionTreeClassifier(),LogisticRegression(),RandomForestClassifier(),SVC(),
        KNeighborsClassifier(n_neighbors=5)]

# all model train the dataset and evalvating the metrics

for mod in models:
    mod.fit(X_train,y_train)
    pr=mod.predict(X_test)
    acc=accuracy_score(pr,y_test)
    prec=precision_score(pr,y_test)
    rec=recall_score(pr,y_test)
    con=confusion_matrix(pr,y_test)
    f1s=f1_score(pr,y_test)
    print(mod)
    print()
    print('accuracy_score: '+str(acc))
    print("precision_score: "+str(prec))
    print("recall_score: "+str(rec))
    print("confusion_matrix")
    print(con)
    print("f1_score",f1s)
    print()
    print()

DecisionTreeClassifier()

accuracy_score: 0.7160751565762005
precision_score: 0.4148471615720524
recall_score: 0.40772532188841204
confusion_matrix
[[1182  268]
 [ 276  190]]
f1_score 0.4112554112554113


LogisticRegression()

accuracy_score: 0.7807933194154488
precision_score: 0.3296943231441048
recall_score: 0.571969696969697
confusion_matrix
[[1345  307]
 [ 113  151]]
f1_score 0.41828254847645435


RandomForestClassifier()

accuracy_score: 0.7526096033402923
precision_score: 0.4388646288209607
recall_score: 0.48086124401913877
confusion_matrix
[[1241  257]
 [ 217  201]]
f1_score 0.4589041095890411


SVC()

accuracy_score: 0.7807933194154488
precision_score: 0.4126637554585153
recall_score: 0.5558823529411765
confusion_matrix
[[1307  269]
 [ 151  189]]
f1_score 0.4736842105263158


KNeighborsClassifier()

accuracy_score: 0.7656576200417536
precision_score: 0.4432314410480349
recall_score: 0.5113350125944585
confusion_matrix
[[1264  255]
 [ 194  203]]
f1_score 0.47485380116959064




In [32]:
# LogisticRegression and SVC are good trained model 

In [33]:
# improving accuracy of the model i using  cross validation for Logistic Regression

from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer
lo=LogisticRegression().fit(X_train,y_train)
scorer = make_scorer(accuracy_score)
scorerf=make_scorer(f1_score)
cros=cross_val_score(lo,X_train,y_train,scoring=scorer,cv=20)
crosf=cross_val_score(lo,X_train,y_train,scoring=scorerf,cv=20)
print("accuracy : ", np.mean(cros))
print("f1_score : ", np.mean(crosf))

accuracy :  0.7762443776498643
f1_score :  0.42003196291457784


In [34]:
# coress validation use for Support vector classifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer
lo=SVC().fit(X_train,y_train)
scorer = make_scorer(accuracy_score)
scorerf=make_scorer(f1_score)
cros=cross_val_score(lo,X_train,y_train,scoring=scorer,cv=20)
crosf=cross_val_score(lo,X_train,y_train,scoring=scorerf,cv=20)
print("accuracy : ", np.mean(cros))
print("f1_score : ", np.mean(crosf))

accuracy :  0.78140759719642
f1_score :  0.48671301654288196


In [40]:
#find 0 and 1 similar values


# Train a random forest classifier to obtain feature importances
rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train, y_train)

# Get feature importances from the trained model
importance_scores = rf_classifier.feature_importances_

# Create a DataFrame to store feature importances
importance_df = pd.DataFrame({'Feature': X_train.columns, 'Importance': importance_scores})

importance_df.reset_index(drop=True, inplace=True)

# Combine importance_df with y_train using the DataFrame's index
combined_df = pd.concat([importance_df, y_train.reset_index(drop=True)], axis=1)

# Separate feature importances for target value 0 and 1 using boolean indexing
importance_df_0 = combined_df[combined_df['target'] == 0].drop(columns='target')
importance_df_1 = combined_df[combined_df['target'] == 1].drop(columns='target')

# Sort by importance to find major relations
major_relations_0 = importance_df_0.sort_values(by='Importance', ascending=False)
major_relations_1 = importance_df_1.sort_values(by='Importance', ascending=False)

# Print or visualize the major relations for target values 0 and 1
print("Major relations for target value 0:")
print(major_relations_0)

print("\nMajor relations for target value 1:")
print(major_relations_1)


Major relations for target value 0:
                      Feature  Importance
5                  experience    0.242537
0                        city    0.202654
1      city_development_index    0.163356
8                last_new_job    0.107749
4             education_level    0.062154
...                       ...         ...
17235                     NaN         NaN
17236                     NaN         NaN
17238                     NaN         NaN
17240                     NaN         NaN
17241                     NaN         NaN

[12923 rows x 2 columns]

Major relations for target value 1:
            Feature  Importance
6      company_size    0.105579
9               NaN         NaN
10              NaN         NaN
11              NaN         NaN
18              NaN         NaN
...             ...         ...
17225           NaN         NaN
17227           NaN         NaN
17234           NaN         NaN
17237           NaN         NaN
17239           NaN         NaN

[4319 rows x

## Challenge 1:

### Major Relations for Target Value 0 (Not looking for job change):

* The DataFrame lists the features along with their importance scores for predicting that the             individual is not looking for a job change.
* For example, features like 'experience', 'city', 'city_development_index', and 'last_new_job' have     relatively high importance scores, indicating they are influential in predicting that someone is not   looking for a job change.
* Some rows show NaN (Not a Number) values, which may indicate missing data or features that were not     considered in the analysis.
### Major Relations for Target Value 1 (Looking for job change):

* Similarly, the DataFrame lists the features and their importance scores for predicting that the         individual is looking for a job change.
* For instance, 'company_size' is highlighted as an important feature for predicting job change.
* Similar to the previous DataFrame, there are rows with NaN values, possibly indicating missing data     or features not included in the analysis.
##### Overall, the output helps identify which features are most important in predicting each target value, providing insights into                                                             the factors influencing job change decisions.








In [41]:
# its challenge 2

import warnings
warnings.filterwarnings("ignore")

In [42]:
de=DecisionTreeClassifier()
de.fit(X_train,y_train)


DecisionTreeClassifier()

In [43]:
# i give unseen data and predict to "Not looking and looking for job"
# any person data you give and predict easly

inputdata=(0.384382,0.789,1,2,0.277741,0.454023,0.327569,0.260638,0.301387)
gh=np.asarray(inputdata)
new=gh.reshape(1,-1)
pr=de.predict(new)
if (pr==0):
    print("Not looking for job change")
else:
    print("Looking for job")


Looking for job


## Challenge 2:

"After providing the features 'city', 'city_development_index', 'relevent_experience', 'enrolled_university', 'education_level', 'experience', 'company_size', 'company_type', and 'last_new_job' with their respective values, the program will determine whether the employee will Not looking or looking for job change."