In [1]:
#import nessary module
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
#read csv file
df=pd.read_csv("heart.csv")

In [3]:
#find how many rows and columns is there in dataset
df.shape

(918, 12)

In [4]:

# check null values in dataset
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [5]:
#information of dataset
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [6]:
# remove warnings
import warnings
warnings.filterwarnings("ignore")

In [7]:
# change the  [object feature] into [int feature] 

from sklearn.preprocessing import LabelEncoder

for col in df.columns:
    if df[col].dtype=='object':
        la=LabelEncoder()
        df[col]=la.fit_transform(df[col])
    

In [8]:
df

    

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              1        140          289          0           1   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           2   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0      172               0      0.0         2             0  
1      156               0      1.0         1             1  
2       98               0      0.0         2             0  
3      108               1      1.5         1             1  
4      122               0      0.0         2             0  
..     ...             ...      ...       ...           ...  
913    132               0      1.2         1             1  
914    141               0      3.4         1             1  
915    115               1      1.2         1             1  
916    174               0      0.0         1             1  
917    173               0      0.0         2             0  

[918 rows x 12 columns]

In [9]:
# find the correlation of one feature to another feature

df.corr()





Age       Sex  ChestPainType  RestingBP  Cholesterol  \
Age             1.000000  0.055750      -0.077150   0.254399    -0.095282   
Sex             0.055750  1.000000      -0.126559   0.005133    -0.200092   
ChestPainType  -0.077150 -0.126559       1.000000  -0.020647     0.067880   
RestingBP       0.254399  0.005133      -0.020647   1.000000     0.100893   
Cholesterol    -0.095282 -0.200092       0.067880   0.100893     1.000000   
FastingBS       0.198039  0.120076      -0.073151   0.070193    -0.260974   
RestingECG     -0.007484  0.071552      -0.072537   0.022656    -0.196544   
MaxHR          -0.382045 -0.189186       0.289123  -0.112135     0.235792   
ExerciseAngina  0.215793  0.190664      -0.354727   0.155101    -0.034166   
Oldpeak         0.258612  0.105734      -0.177377   0.164803     0.050148   
ST_Slope       -0.268264 -0.150693       0.213521  -0.075162     0.111471   
HeartDisease    0.282039  0.305445      -0.386828   0.107589    -0.232741   

                FastingBS  RestingECG     MaxHR  ExerciseAngina   Oldpeak  \
Age              0.198039   -0.007484 -0.382045        0.215793  0.258612   
Sex              0.120076    0.071552 -0.189186        0.190664  0.105734   
ChestPainType   -0.073151   -0.072537  0.289123       -0.354727 -0.177377   
RestingBP        0.070193    0.022656 -0.112135        0.155101  0.164803   
Cholesterol     -0.260974   -0.196544  0.235792       -0.034166  0.050148   
FastingBS        1.000000    0.087050 -0.131438        0.060451  0.052698   
RestingECG       0.087050    1.000000 -0.179276        0.077500 -0.020438   
MaxHR           -0.131438   -0.179276  1.000000       -0.370425 -0.160691   
ExerciseAngina   0.060451    0.077500 -0.370425        1.000000  0.408752   
Oldpeak          0.052698   -0.020438 -0.160691        0.408752  1.000000   
ST_Slope        -0.175774   -0.006778  0.343419       -0.428706 -0.501921   
HeartDisease     0.267291    0.057384 -0.400421        0.494282  0.403951   

                ST_Slope  HeartDisease  
Age            -0.268264      0.282039  
Sex            -0.150693      0.305445  
ChestPainType   0.213521     -0.386828  
RestingBP      -0.075162      0.107589  
Cholesterol     0.111471     -0.232741  
FastingBS      -0.175774      0.267291  
RestingECG     -0.006778      0.057384  
MaxHR           0.343419     -0.400421  
ExerciseAngina -0.428706      0.494282  
Oldpeak        -0.501921      0.403951  
ST_Slope        1.000000     -0.558771  
HeartDisease   -0.558771      1.000000

In [10]:
# find the correlation dependent variable and variable
c=df.corr().HeartDisease

In [11]:
abs(c)


Age               0.282039
Sex               0.305445
ChestPainType     0.386828
RestingBP         0.107589
Cholesterol       0.232741
FastingBS         0.267291
RestingECG        0.057384
MaxHR             0.400421
ExerciseAngina    0.494282
Oldpeak           0.403951
ST_Slope          0.558771
HeartDisease      1.000000
Name: HeartDisease, dtype: float64

In [12]:
#drop the porrest correlation features

f=['Age','Cholesterol','RestingECG','RestingBP','FastingBS']
df.drop(columns=f, inplace=True)

In [13]:
df

Sex  ChestPainType  MaxHR  ExerciseAngina  Oldpeak  ST_Slope  \
0      1              1    172               0      0.0         2   
1      0              2    156               0      1.0         1   
2      1              1     98               0      0.0         2   
3      0              0    108               1      1.5         1   
4      1              2    122               0      0.0         2   
..   ...            ...    ...             ...      ...       ...   
913    1              3    132               0      1.2         1   
914    1              0    141               0      3.4         1   
915    1              0    115               1      1.2         1   
916    0              1    174               0      0.0         1   
917    1              2    173               0      0.0         2   

     HeartDisease  
0               0  
1               1  
2               0  
3               1  
4               0  
..            ...  
913             1  
914             1  
915             1  
916             1  
917             0  

[918 rows x 7 columns]

In [14]:
#seprate the independent variable and dependent variable

X=df.iloc[:,:6].values

In [15]:
y=df.iloc[:,6].values

In [16]:
# split the train ,test and import module
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y  ,test_size=0.2,random_state=42)

In [17]:
#build the model and train the dataset
from sklearn.ensemble import RandomForestClassifier
ran=RandomForestClassifier()
ran.fit(X_train,y_train)

RandomForestClassifier()

In [18]:
#check the train feature
e=ran.predict(X_train)

In [19]:
#find the accuracy
#its a balanced dataset so use accuracy metrics
from sklearn.metrics import accuracy_score
acc=accuracy_score(e,y_train)

In [20]:
acc

0.9904632152588556

In [21]:
# give a unseen dataset and predict the value 
tesx=ran.predict(X_test)

In [22]:
# chek the unseen dataset  accuracy
m=accuracy_score(tesx,y_test)

In [23]:
m

0.8097826086956522

In [24]:
# try another model

from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(X_train,y_train)

LogisticRegression()

In [25]:
logt=log.predict(X_test)

In [26]:
ac=accuracy_score(logt,y_test)
ac

0.8043478260869565

In [27]:
from sklearn.tree import DecisionTreeClassifier
des=DecisionTreeClassifier()
des.fit(X_train,y_train)
desp=des.predict(X_test)


In [28]:
accd=accuracy_score(desp,y_test)

In [29]:
accd

0.7717391304347826

In [30]:
from sklearn.svm import SVC
sv=SVC()
sv.fit(X_train,y_train)
svp=sv.predict(X_test)
sva=accuracy_score(svp,y_test)
sva

0.6793478260869565

In [31]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier()
kn.fit(X_train,y_train)
knp=kn.predict(X_test)
kna=accuracy_score(knp,y_test)
kna

0.8206521739130435

In [32]:
# before i using seprate to seprate moduel
#this time i am using python for loop and similar code write find the accuracy of all models

models=[KNeighborsClassifier(),SVC(),DecisionTreeClassifier(),RandomForestClassifier(),LogisticRegression()]

for mod in models:
    
    mod.fit(X_train,y_train)
    gh=mod.predict(X_test)
    acc=accuracy_score(gh,y_test)
    print("the accuracyn of the"+" "+str(mod)+"="+" " +str(acc))
    
    
    

the accuracyn of the KNeighborsClassifier()= 0.8206521739130435
the accuracyn of the SVC()= 0.6793478260869565
the accuracyn of the DecisionTreeClassifier()= 0.7717391304347826
the accuracyn of the RandomForestClassifier()= 0.8206521739130435
the accuracyn of the LogisticRegression()= 0.8043478260869565


In [35]:
#find tp,tn,fp,fn terms 

from sklearn.metrics import confusion_matrix

In [37]:
for modf in models:
    modf.fit(X_train, y_train)
    j = modf.predict(X_test)
    hj = confusion_matrix(j, y_test)
    print(modf)
    print( hj)

KNeighborsClassifier()
[[65 21]
 [12 86]]
SVC()
[[44 26]
 [33 81]]
DecisionTreeClassifier()
[[68 35]
 [ 9 72]]
RandomForestClassifier()
[[67 25]
 [10 82]]
LogisticRegression()
[[67 26]
 [10 81]]


In [48]:
#finally give one input and check the output
#the good mode is KNeighborsClassifier,so i used this model
inputdata=(1,0,115,1,1.2,1)
gh=np.asarray(inputdata)
new=gh.reshape(1,-1)
pr=kn.predict(new)
if (pr==0):
    print("heart disese negative")
else:
    print("heart disese positive")

heart disese positive
